
version: '3'

services:
    papermill:
        restart: always
        build: .
        command: "gunicorn app:app --bind 0.0.0.0:5000 --reload --log-level=DEBUG"
        env_file:
            - .env-file
        ports:
            - "80:5000"
        networks:
            - netto

networks:
  netto:

volumes:
  redis-data: