
version: '3'

services:
    papermill:
        restart: always
        build: .
        command: "python app.py"
        ports:
            - "80:80"
        networks:
            - netto

    redis:
        image: redis:alpine
        command: ["redis-server", "--appendonly", "yes"]
        hostname: redis
        networks:
        - netto
        volumes:
        - redis-data:/data

networks:
  netto:

volumes:
  redis-data: